version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_shared
    ports:
      - 3306:3306
    networks:
      - appnet
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p$$MYSQL_ROOT_PASSWORD","--protocol","tcp" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  spring-app:
    build: .
    ports:
      - 8080:8080
    networks:
      - appnet
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/simple_shared
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
networks:
  appnet: {}

